# Menu config

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  name = "Posts"
  url = "/posts/"
  # title will be shown when you hover on this menu link.
  title = ""
  weight = 1
  
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 2

[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 3

[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "Series"
  url = "/series/"
  title = ""
  weight = 4
  
[[main]]
  identifier = "meetme"
  pre = ""
  post = ""
  name = "Meet Me"
  url = "/meetme/"
  title = ""
  weight = 7

[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
  weight = 8

[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github fa-fw'></i>"
  post = ""
  name = ""
  url = "https://github.com/TheDoubleH/thedoubleh.dev"
  title = "GitHub"
  weight = 9

[[footer]]
  identifier = "cookies"
  pre = "<i class='fab fa-cookie fa-fw'></i>"
  post = ""
  name = ""
  url = "cookie-policy"
  title = "GitHub"
  weight = 1