baseURL = 'https://TheDoubleH.dev/'
languageCode = 'en-us'
title = 'Henriks home in cyberspace'
theme = 'DoIt'
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # DoIt theme version
  version = "0.2.X"
  # site description
  description = "Ramblings about Microsoft Dynamics 365 Business Central"
  # site keywords
  keywords = ["Microsoft Dynamics 365 Business Central", "Navision", "Microsoft Dynamics-NAV"]

  [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "Henrik's home in Cyberspace"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='far fa-edit fa-fw'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = true
  
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1
    
  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Henrik's home in Cyberspace"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10

    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "henrik@helgesen.us"
      # URL of avatar shown in home page
      #avatarURL = "/images/avatar.webp"
      # title shown in home page (HTML format is supported)
      title = "Henriks Home in Cyberspace"
      # subtitle shown in home page
      subtitle = "With over 20 years of doing this, I should have something to share ..."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "<i>Welcome to my humble abode ...</i>"

    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 7

  # Social config in home page
  [params.social]
    GitHub = "TheDoubleH"
    Linkedin = "TheDoubleH"
    Twitter = "TheDoubleH"
    Youtubechannel = ""
    Paypal = "TheDoubleH"
    BuyMeACoffee = "TheDoubleH"
    Email = "henrik@helgesen.us"
    RSS = true

  # Search Configuration
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia", "fuse")
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      #  https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

# Menu config
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link.
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "series"
    pre = ""
    post = ""
    name = "Series"
    url = "/series/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "showcase"
    pre = ""
    post = ""
    name = "Showcase"
    url = "/showcase/"
    title = ""
    weight = 6
  [[menu.main]]
    identifier = "documentation"
    pre = ""
    post = ""
    name = "Docs"
    url = "/categories/documentation/"
    title = ""
    weight = 7
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 8
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/TheDoubleH/thedoubleh.dev"
    title = "GitHub"
    weight = 9    

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
